### ISSUE TITLE
Can't parse on reload?

### ISSUE THREAD

**Issue by bengolds** [joeandaverde/elm-webpack-project-loader#15]
I'm not sure what's wrong here (and our webpack config is enormous), so I figured I'd just post here in case this is familiar to you. If not, I'll keep tracking it down :)

I'm running `elm-webpack-project-loader`. On first run, it works great. On any recompile in watch mode, I get:
```
ERROR in ../media/visualizations/Interactives.elmproj 2:16
Module parse failed: Unexpected token (2:16)
You may need an appropriate loader to handle this file type.
| {
>   "elm-json-dir": "./",
|   "main-modules": [
|     "./GridFill/SolutionMode.elm",
```

I've got `module.noParse` set to `/.elmproj$/`, so I'm not sure why it's all of a sudden struggling to parse this. Any familiarity?

**Comment by bengolds** [comment]
This was fixed for me by removing the `noParse` line...

**Comment by joeandaverde** [comment]
Thanks. Please let me know if this should be handled differently.
