### ISSUE TITLE
Allow local elm installs

### ISSUE THREAD

**Issue by paulstatezny** [joeandaverde/elm-webpack-project-loader#8]
First off, thanks for creating this loader!

It's good practice to include all dependencies locally in a project and call them from there. (In this case, installing Elm as a dependency of the project, and then calling it from `project_root/node_modules/.bin/elm-make`.

This loader assumes `elm-make` is installed globally. It would be nice to have a `pathToMake` option like [elm-webpack-loader](https://github.com/elm-community/elm-webpack-loader#upstream-options) so this could be achieved.

**Comment by joeandaverde** [comment]
Sounds good!

**Comment by paulstatezny** [comment]
Actually, I might be wrong about this -- I was having an issue and then I deleted `node_modules` and `elm-stuff` and reinstalled dependencies, and the problem went away.

Gotta love system state. :-(

**Comment by witoldsz** [comment]
It looks like when the the command, i.e. `webpack`, is launched from within a `npm run …` script, all the `./node_modules/.bin` executable files are within the `PATH` environment, so the local `elm-make` is used. There is no need to explicitly specify the path.

**Comment by alexmunda** [comment]
@witoldsz has a good solution. Closing.
